#ifndef __BSP_EXIT_H__
#define __BSP_EXIT_H__

#define KEY1_EXIT_PORT		GPIOA
#define KEY1_EXIT_PIN		GPIO_PIN_0
#define KEY1_EXIT_MODE		GPIO_MODE_IT_RISING
#define KEY1_EXIT_IRQ		EXTI0_IRQn
#define KEY1_EXIT_PULL		GPIO_NOPULL

#define KEY2_EXIT_PORT		GPIOC
#define KEY2_EXIT_PIN		GPIO_PIN_13
#define KEY2_EXIT_MODE		GPIO_MODE_IT_RISING
#define KEY2_EXIT_IRQ		EXTI15_10_IRQn
#define KEY2_EXIT_PULL		GPIO_NOPULL


void KEY1_EXIT_INIT(void);
void KEY2_EXIT_INIT(void);

#endif /* __BSP_EXIT_H__ */

